# Generated by Django 3.1.2 on 2021-06-29 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(default='', max_length=32, verbose_name='应用名')),
                ('did', models.IntegerField(default=0, verbose_name='dtree_id')),
                ('ip', models.CharField(default='', max_length=1024, null=True, unique=True, verbose_name='部署IP')),
                ('source', models.CharField(default='', max_length=32, verbose_name='源服务器地址')),
                ('status', models.BooleanField(db_column='status', default=False)),
                ('dtree_info', models.CharField(blank=True, default='', max_length=1024, verbose_name='dtree信息')),
            ],
            options={
                'verbose_name': '应用管理',
                'verbose_name_plural': '应用管理',
            },
        ),
    ]
