# Generated by Django 3.1.2 on 2021-06-29 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='dtree_info',
            field=models.CharField(blank=True, default='', max_length=1024, null=True, verbose_name='dtree信息'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='ip',
            field=models.CharField(default='', max_length=1024, verbose_name='部署IP'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='source',
            field=models.CharField(blank=True, default='', max_length=32, null=True, verbose_name='源服务器地址'),
        ),
    ]
