# Generated by Django 3.1.2 on 2021-08-03 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20210629_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='paas_name',
            field=models.CharField(blank=True, default='', max_length=32, null=True, verbose_name='服务器名'),
        ),
    ]
