# Generated by Django 3.1.2 on 2021-08-13 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_projects_paas_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='dtree_info',
        ),
        migrations.AddField(
            model_name='projects',
            name='r_port',
            field=models.IntegerField(blank=True, default=22, max_length=32, null=True, verbose_name='源ssh_port'),
        ),
        migrations.AddField(
            model_name='projects',
            name='s_code',
            field=models.CharField(blank=True, default='', max_length=32, null=True, verbose_name='源代码path'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='source',
            field=models.CharField(blank=True, default='', max_length=32, null=True, verbose_name='源服务器IP'),
        ),
    ]
