# Generated by Django 3.1.2 on 2021-08-13 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20210813_1146'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projects',
            old_name='r_port',
            new_name='s_port',
        ),
    ]
