# Generated by Django 3.1.2 on 2021-06-29 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='任务名称')),
                ('creator', models.CharField(blank=True, default='', max_length=32, null=True, verbose_name='创建者')),
                ('playbook', models.CharField(max_length=1024, verbose_name='关联playbook')),
                ('born', models.DateTimeField(auto_now_add=True, max_length=32, null=True, verbose_name='创建时间')),
                ('last', models.DateTimeField(auto_now=True, max_length=32, null=True, verbose_name='上次执行时间')),
                ('app_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.projects', verbose_name='关联应用')),
            ],
            options={
                'verbose_name': '任务列表',
                'verbose_name_plural': '任务列表',
            },
        ),
    ]
